# Generated by Django 2.2 on 2021-06-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book_img/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.SlugField(max_length=10),
        ),
    ]
