# Generated by Django 2.2 on 2021-06-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, default='author_img/person.jpg', null=True, upload_to='author_img/'),
        ),
    ]
