# Generated by Django 2.2 on 2021-06-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_author_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publishing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(default='author_img/person.jpg', upload_to='author_img/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='book_img/book.jpg', upload_to='book_img/'),
        ),
    ]
