# Generated by Django 2.2 on 2021-06-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20210623_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishing',
            name='title',
            field=models.CharField(default='Something', max_length=64),
        ),
    ]
