# Generated by Django 2.2 on 2021-06-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20210623_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishing',
            name='headquarter',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
