# Generated by Django 2.2 on 2021-06-23 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20210623_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publishing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publishing', to='books.Publishing'),
        ),
    ]
