# Generated by Django 2.2 on 2021-06-25 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_publishing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publishing',
        ),
        migrations.DeleteModel(
            name='Publishing',
        ),
    ]
